//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEducation.AuthServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimType
    {
        public ClaimType()
        {
            this.UserClaims = new HashSet<UserClaim>();
        }
    
        public System.Guid ClaimTypeId { get; set; }
        public string ClaimType1 { get; set; }
        public string ClaimUri { get; set; }
        public bool IsRegularClaim { get; set; }
    
        public virtual ICollection<UserClaim> UserClaims { get; set; }
    }
}
