//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEducation.AuthServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserClaim
    {
        public System.Guid UserClaimId { get; set; }
        public System.Guid UserAccountId { get; set; }
        public System.Guid ClaimTypeId { get; set; }
        public string ResourceName { get; set; }
        public string Right { get; set; }
    
        public virtual ClaimType ClaimType { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
